### PR TITLE
fix some issues mentioned by the analysis tool

### PR DESCRIPTION
**Pull request by leogtzr**

### CODE REVIEW

**Comment by kayrus** [comment]
@leogtzr thanks for your contribution. May I ask you about the tool name? I'm going to write tests, and it is a good idea to run static code analysis as well.

**Comment by leogtzr** [comment]
I ran this first:
```
go test -v -coverprofile cover.out ./putty/... && go tool cover -html=cover.out -o cover.html
```

then this:
```
0 [23:30]leo@leonidas ~/go_source/src/putty (master) $ golint -min_confidence 0.8 .
main.go:22:7: exported const MaxKeyBlobSize should have comment or be unexported
main.go:23:7: exported const MaxKeyBlobLines should have comment or be unexported
main.go:25:6: exported type Key should have comment or be unexported
0 [23:31]leo@leonidas ~/go_source/src/putty (master)
```

**Comment by leogtzr** [comment]
To install golint:

```
 go get -u golang.org/x/lint/golint
```

**Comment by kayrus** [comment]
thanks. I'll appreciate if you can help me with the godoc as well. and with the error messages. I believe they should start with the lowercase and have a `putty:` prefix.

**Comment by leogtzr** [comment]
Sure thing, I will submit another PR tomorrow morning and see if I can help you out with some tests :)

**Comment by leogtzr** [comment]
Can you please show me how do you generate the private key from the command line? 

when I run the program from the README.md I get this:
```
2019/05/30 15:47:19 Calculated MAC "736ff43ed23775819134f8a779741ac0e608f5c1" doesn't correspond to "87e1d4f6394e1d0071a9d10b811881a78b43167f"
```

**Pull request merged**
